/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_me_s1rius_ffmpeglib_FFmpegHelper
#define _Included_me_s1rius_ffmpeglib_FFmpegHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_s1rius_ffmpeglib3_FFmpegHelper
 * Method:    run
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_me_s1rius_ffmpeglib_FFmpegHelper_run (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
